os: linux
dist: focal
group: edge
language: generic
git:
  depth: 1
addons:
  apt:
    update:
      - true
    packages:
      - aria2
      - zstd
      - xz-utils
addons:
  apt:
    update:
      - true
    packages:
      - aria2
      - zstd
      - xz-utils
services:
  - docker
before_install:
  - docker pull fr3akyphantom/droid-builder:latest
before_script:
  - cd $HOME && mkdir twrp
  - wget -q https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.4.0-20201103/MinimalOmniRecovery-twrp-8.1-norepo-20201103.tzst.aa
  -O $HOME/twrp.tzst
  - tar --zstd -xf twrp.tzst --directory $HOME/twrp/ && rm twrp.tzst
script:
  - cd $HOME/twrp/ && git clone https://github.com/thespider2/android_device_iris65.git device/lava/iris65
  - git clone https://github.com/TwrpBuilder/android_device_generic_twrpbuilder.git device/generic/twrpbuilder
  - git clone https://github.com/omnirom/android_bootable_recovery.git -b android-8.1 --depth 1 bootable/recovery 
  - |
    docker run --rm -i -v "$(pwd):/root/twrp/:rw,z" surendrajat/twrp-builder bash << EOF
    cd /root/twrp/
    source build/envsetup.sh && lunch omni_iris65-eng && make -j16 recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/iris65/recovery.img $HOME/twrp/TWRP-$version-iris65-$(date +"%Y%m%d").img

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "f269b25ffa7b769d0d03efe180338b2655ffca8b"
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: thespider2/android_device_iris65
    branch: master
branches:
  except:
    - /^(?i:untagged)-.*$/
